// Runs ALG-18 (frontend/src/lib/commercial/funnelMetrics.js) on facts generated by
// seed_hu15_demo.py, for its coverage check. Input: a JSON file { [caller]: { now, proyectos, facts } }.
// Output: { [caller]: { semana, mes, año } }, each the full FunnelMetrics with no filters.
import { readFileSync } from "node:fs";
import { register } from "node:module";

// The frontend's lib/ uses extensionless imports, which Vite resolves and plain Node does not.
register("data:text/javascript," + encodeURIComponent(`
export async function resolve(specifier, context, next) {
  try {
    return await next(specifier, context);
  } catch (error) {
    if (error.code === "ERR_MODULE_NOT_FOUND" && specifier.startsWith(".") && !/\\.[cm]?js$/.test(specifier)) {
      return next(specifier + ".js", context);
    }
    throw error;
  }
}`));

const moduleUrl = new URL("../../frontend/src/lib/commercial/funnelMetrics.js", import.meta.url);
const { computeFunnelMetrics } = await import(moduleUrl.href);

const input = JSON.parse(readFileSync(process.argv[2], "utf-8"));
const filtros = { proyecto_id: null, afinidad: [], capacidad: [], prioridad: [] };
const output = {};
for (const [caller, { now, proyectos, facts }] of Object.entries(input)) {
  output[caller] = Object.fromEntries(["semana", "mes", "año"].map((granularidad) =>
    [granularidad, computeFunnelMetrics({ facts, proyectos, filtros, now, granularidad })]));
}
process.stdout.write(JSON.stringify(output));
