export function buildFinancialInput(input = {}) {
  return {
    birth_date: input.birth_date,
    ingreso_mensual: input.ingreso_mensual,
    deuda_mensual: input.deuda_mensual,
    edad: input.edad,
    ahorro_disponible: input.ahorro_disponible,
    property_value: input.property_value,
    property_value_unit: input.property_value_unit,
    property_value_uf: input.property_value_uf,
    property_value_clp: input.property_value_clp,
    property_value_source: input.property_value_source,
    plazo_credito_hipotecario: input.plazo_credito_hipotecario,
    dividendo_estimado: input.dividendo_estimado,
    dividendo_esperado: input.dividendo_esperado,
    dividendo_estimado_origen: input.dividendo_estimado_origen,
    dividendo_estimado_calculado: input.dividendo_estimado_calculado,
    dividendo_estimado_manual: input.dividendo_estimado_manual,
    dividendo_tasa_anual_referencial: input.dividendo_tasa_anual_referencial,
    dividendo_monto_credito_estimado_clp: input.dividendo_monto_credito_estimado_clp,
    dividendo_monto_credito_estimado_uf: input.dividendo_monto_credito_estimado_uf,
    dividendo_uf_referencial_clp: input.dividendo_uf_referencial_clp,
    anonymous_flow_id: input.anonymous_flow_id,
    comuna_objetivo: input.comuna_objetivo,
    tipo_contrato: input.tipo_contrato,
    continuidad_laboral: input.continuidad_laboral,
    morosidad_actual: input.morosidad_actual,
    monto_morosidad: input.monto_morosidad,
    antiguedad_morosidad: input.antiguedad_morosidad,
    complemento_renta: input.complemento_renta,
    ingreso_mensual_complementario: input.ingreso_mensual_complementario,
    deuda_mensual_complementario: input.deuda_mensual_complementario,
    tipo_contrato_complementario: input.tipo_contrato_complementario,
    continuidad_laboral_complementario:
      input.continuidad_laboral_complementario,
    morosidad_complementario: input.morosidad_complementario,
    relacion_complementario: input.relacion_complementario,
    declara_patrimonio: input.declara_patrimonio,
    valor_vehiculos: input.valor_vehiculos,
    valor_inmuebles: input.valor_inmuebles,
    patrimonio_unit: input.patrimonio_unit,
    plazo_compra: input.plazo_compra,
    tiene_propiedad_vista: input.tiene_propiedad_vista,
    vivienda_nueva: input.vivienda_nueva,
    pie_en_cuotas_interes: input.pie_en_cuotas_interes,
    consentimiento: input.consentimiento,
    uf_value_clp: input.uf_value_clp,
  };
}
